### ISSUE TITLE
Add note in BUILD.md about running locally

### ISSUE THREAD

**Issue by cllns** [firstlook/autocanary#11]
`BUILD.md` tells you how to build `AutoCanary.app`, which is great for releasing, but not developing. 

For development, if you want to run the app locally, you can run `python autocanary.py` (I imagine... I currently have the issue in #6).

Can you add a note about that in `BUILD.md` (or maybe make a `CONTRIBUTING.md`)? I'm not sure of the wording, or how it'd work on Windows, which I why I didn't open PR.

**Comment by micahflee** [comment]
Good idea.
