### ISSUE TITLE
Update disclaimer section?

### ISSUE THREAD

**Issue by ghost** [firstlook/autocanary#14]
Hey, after [Reddit](https://www.reddit.com/r/IAmA/comments/4dcm55/we_are_aclu_lawyers_and_nick_merrill_of_calyx/) case, maybe you should update the disclaimer?

"This is the big murky legal question. Frankly, nobody really knows how this would go down in court."

**Comment by micahflee** [comment]
Good point.

**Comment by micahflee** [comment]
I just consulted an EFF lawyer about this. It seems that the legal situation hasn't actually changed much, and because so much is secret it still remains "murky". So, for the time being, I'm going to keep the same disclaimer.
