### ISSUE TITLE
Add Automatic Sign-Up to Canary Watch

### ISSUE THREAD

**Issue by headhntr** [firstlook/autocanary#3]
Canary Watch is an warrant canary tracking website - https://canarywatch.org/

Consider adding language to suggest signing up for Canary Watch or adding a field in the application to do this.

**Comment by syndikal** [comment]
the [submission page](https://canarywatch.org/submission.html) on their website lists an email address and requests an already-existing link to where the canary statement can be found. adding a field to do this is tricky if the user hasn't already published the canary statement

**Comment by micahflee** [comment]
Canary Watch is no more: https://www.eff.org/deeplinks/2016/05/canary-watch-one-year-later
