### ISSUE TITLE
[bug] Unicode error

### ISSUE THREAD

**Issue by Taipo** [firstlook/autocanary#9]
u2019 and U+2026 so far prevent signing from completion. There may be more.

`UnicodeEncodeError: 'ascii' codec can't encode character u'\u2026' in position 833: ordinal not in range(128)`
`UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 575: ordinal not in range(128)`

**Comment by micahflee** [comment]
Hey @Taipo, can you also instructions on how to reproduce this? It looks like either the message you're entering in AutoCanary (or maybe the user ID on your PGP key?) uses unicode. I want to reproduce the same error so I can fix it.

**Comment by Taipo** [comment]
Just simple use left and right single quotations, or a horizontal ellipsis in the text status field, will trigger the error.

i.e ‘Test’… (error log only prints the first instance of unicode it finds, in this case its the left single quote)

Error log shows some sort of output encoding error:

> Traceback (most recent call last):
> File "autocanary\autocanary.pyc", line 292, in sign_once_clicked
> File "autocanary\autocanary.pyc", line 335, in sign
> UnicodeEncodeError: 'ascii' codec can't encode character u'\u2018' in position 0: ordinal not in 
> range(128)
